### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by Fraklapince** [unparagoned/cloudtuya#1]
hello,

your project seems to be interesting, but you say in your description: Just using your email and pass.

by reading your code we see the need of differents files : keys.json and devices.json with undocumented structure, it seems to need keys and associated values like 
.userName, password, bizType, countryCode, region, for keys.json file.

could you please precise all the files structures needed ?
why not alls the possibility for parameters like bizType, countruCode, region and others.

with only our Tuya/Smart mail and password, it wasn't usable.

Regards,
Frak

**Comment by unparagoned** [comment]
You are right you need those other variables. But the docs should point you towards what options there are. The comment about only needing those variables is vs the device key which required mitma.

**Comment by xremix** [comment]
@unparagoned  thanks for providing this nice project. 

@Fraklapince  I started taking a look at how everything works and made a fork with an existing tutorial and `example.json`. You can check out [this fork](https://github.com/xremix/cloudtuya) and hopefully this gives you some insights.
