### ISSUE TITLE
Please support for wattmeter.

### ISSUE THREAD

**Issue by havrla** [unparagoned/cloudtuya#10]
Helooo,
Please add support for wattmeter.

No data  Voltage, Current, Power....

  cloudtuya { payload: { devices: [ [Object] ], scenes: [] },
  cloudtuya   header: { code: 'SUCCESS', payloadVersion: 1 } } +3s
  cloudtuya [ { data: { online: true, state: false },
  cloudtuya     name: '2dinwattletr',
  cloudtuya     icon: 'https://images.tuyaeu.com/smart/product_icon/cz.png',
  cloudtuya     id: '02448046bcddc25938da',
  cloudtuya     dev_type: 'switch',
  cloudtuya     ha_type: 'switch' } ] +21ms
  cloudtuya prefilter [{"data":{"online":true,"state":false},"name":"2dinwattletr","icon":"https://images.tuyaeu.com/smart/product_icon/cz.png","id":"02448046bcddc25938da","dev_type":"switch","ha_type":"switch"}] +14ms

I can provide a cloud account with a wattmeter connected.

Thankssss
Havrla@lhotkanet.cz

**Comment by unparagoned** [comment]
From what is returned, I'm not sure how to add support for the information you want. Also, this project is based upon https://github.com/PaulAnnekov/tuyaha and there doesn't appear to be any additional support for wattmeters.

**Comment by havrla** [comment]
Heloo
Well, somehow it must work when the mobile application displays wattmer data.
Maybe another question or another answer.
I can provide an account with a connected wattmeter to develop the expansion.
Email for Tuya account with wattmeter: havrla@lhotkanet.cz

And add
[https://github.com/PaulAnnekov/tuyaha/issues/52](url)

Thanks thanks thanks...

**Comment by unparagoned** [comment]
The mobile apps use a different api/system than the API we are using. I don't think there are any officially released details for the API we are using, and it's been figured out by studying other tools that use it. I've spent quite a bit of time trying to see if there are other hidden details or controls for items like your wattmeter or some color lights without much success. I found out that the API might not tell your enough details about color lights but you can still set the color if you know how. But that won't help with reading values from a device.
