### ISSUE TITLE
Get accesstoken failed.

### ISSUE THREAD

**Issue by banavalikar** [unparagoned/cloudtuya#12]
I get the following. And I am definitely entering the correct username and password.

![image](https://user-images.githubusercontent.com/10076518/97973667-557a4400-1dbe-11eb-8ece-2319b91abe5e.png)

![image](https://user-images.githubusercontent.com/10076518/97974023-eb15d380-1dbe-11eb-9b77-7b849f23fd59.png)

**Comment by unparagoned** [comment]
I would double check your login and pass, otherwise, maybe you need to look at the region, app, country code. 
You can get more information with the following.
win ```set DEBUG=* && node example.js ```
linux ```DEBUG=* node example.js ```

**Comment by banavalikar** [comment]
Everything was correct. 

For people trying to get the Tuya Cloud API working, the advice here 100% works - https://developer.tuya.com/en/docs/iot/open-api/quick-start/quick-start1?id=K95ztz9u9t89n

You have to make 2 calls -

To get a session
Control the LED
Plus one optional call to find out the control API your device supports.

You can export the API from Postman and use it in your project.

Hope this helps.
