### ISSUE TITLE
Color mode support for lights

### ISSUE THREAD

**Issue by ndg63276** [unparagoned/cloudtuya#15]
Hey, I've been playing with tuya cloud control (https://github.com/ndg63276/smartlife) and this is a really useful repo.

I have been looking at lighting control. I see in this repo you have these commands:
* turnOnOff
* brightnessSet

And in njsTuya you have:
* colorSet
* temperatureSet

My bulbs don't have color temperature support, but the other 3 all work great. But I was wondering about color mode. If you send a colorSet command, it switches to "color" mode, but I then cannot set my bulbs back into "white" mode. I guess the answer is to send a temperatureSet command, but it fails for me as my bulbs don't do color temperature.

But if you know of any way to switch between color modes, or know of any documentation, I would love to know about it. If not, no worries. Keep up the good work!

**Comment by unparagoned** [comment]
The best source and reference is https://github.com/PaulAnnekov/tuyaha. If you can't find your answer let me know and I'll have a look.

**Comment by ndg63276** [comment]
Thanks, that's really useful. I spent quite a bit of time going between links of different repos, so it's good to know the source! Will close the ticket.

(I have now bought a light with color temperature support, so if anyone cares, sending a "colorTemperatureSet" command does change the light to "white" mode.)
