### ISSUE TITLE
Error running on RPi armv6l

### ISSUE THREAD

**Issue by Electrik-rich546456** [unparagoned/cloudtuya#18]
Hello, I am getting this error `node example.js
undefined
(node:10882) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'brightness' of undefined
    at Light.getBrightness (/home/pi/cloudtuya/devices/light.js:10:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
It created the `devices.json` successfully but it just fails to turn lights off how do i fix it.
Ideally i want two script example to turn on and off

**Comment by unparagoned** [comment]
Can you run with ```DEBUG=* node YOURSCRIPT.js```

**Comment by Electrik-rich546456** [comment]
I don't know what that means. 
Where does it go?
In the file?
Or in the CLI

**Comment by unparagoned** [comment]
Yep in the command line. Run your script with the ```DEBUG=*``` prefix
