### ISSUE TITLE
getSkills function fails

### ISSUE THREAD

**Issue by andrea1984** [unparagoned/cloudtuya#19]
the getSkill function fail on smart_life devices, the output of the post request is:

cloudtuya {
  cloudtuya   payload: {},
  cloudtuya   header: {
  cloudtuya     msg: 'you can discovery once in 600 seconds',
  cloudtuya     code: 'FrequentlyInvoke',
  cloudtuya     payloadVersion: 1
  cloudtuya   }
  cloudtuya } +70ms

So it's impossible to know the state (or is possible only once every 10 minutes).

**Comment by unparagoned** [comment]
Yep you can only get the state once every 10 minutes. I think you are supposed to query everything at the start and keep your own record of the states.
